config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :trees
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'

  get 'home/pricing'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tree.rb
class Tree < ApplicationRecord
  validates :instagram, presence: true, format: { with: %r{\Ahttps?://\S+\z}, message: 'Invalid URL format' }

  validates :x, presence: true, format: { with: %r{\Ahttps?://\S+\z}, message: 'Invalid URL format' }

  validates :youtube, presence: true, format: { with: %r{\Ahttps?://\S+\z}, message: 'Invalid URL format' }

  validates :name, presence: true, length: { minimum: 4, message: 'Too short name' }

  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :trees
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: %i[pricing]

  def index; end

  def pricing; end
end

app/controllers/trees_controller.rb
# frozen_string_literal: true

# Controller for LinkTree
class TreesController < ApplicationController
  before_action :set_tree, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[index new edit update destroy]

  # GET /trees or /trees.json
  def index
    @trees = current_user.trees
  end

  # GET /trees/1 or /trees/1.json
  def show; end

  # GET /trees/new
  def new
    @tree = Tree.new
  end

  # GET /trees/1/edit
  def edit; end

  # POST /trees or /trees.json
  def create
    @tree = Tree.new(tree_params)

    respond_to do |format|
      if @tree.save
        format.html { redirect_to tree_url(@tree), notice: 'Tree was successfully created.' }
        format.json { render :show, status: :created, location: @tree }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trees/1 or /trees/1.json
  def update
    respond_to do |format|
      if @tree.update(tree_params)
        format.html { redirect_to tree_url(@tree), notice: 'Tree was successfully updated.' }
        format.json { render :show, status: :ok, location: @tree }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trees/1 or /trees/1.json
  def destroy
    @tree.destroy!

    respond_to do |format|
      format.html { redirect_to trees_url, notice: 'Tree was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tree
    @tree = Tree.friendly.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tree_params
    params.require(:tree).permit(:name, :x, :instagram, :youtube, :user_id, :style)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/trees_helper.rb
module TreesHelper
end

app/views/home/index.html.erb
<div >
    <h1>Welcome to LinkTree Clone</h1>
<p>Link in bio tool: Everything you are, in one simple link</p>

<%=  link_to "Get Started", new_tree_path %>
</div>

app/views/home/pricing.html.erb
<div >
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
      <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
          <div class="card-header py-3">
            <h4 class="my-0 fw-normal">Free</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">$0<small class="text-body-secondary fw-light">/mo</small></h1>
            <ul class="list-unstyled mt-3 mb-4">
              <li>10 users included</li>
              <li>2 GB of storage</li>
              <li>Email support</li>
              <li>Help center access</li>
            </ul>
            <button type="button" class="w-100 btn btn-lg btn-outline-primary">Sign up for free</button>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
          <div class="card-header py-3">
            <h4 class="my-0 fw-normal">Pro</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">$15<small class="text-body-secondary fw-light">/mo</small></h1>
            <ul class="list-unstyled mt-3 mb-4">
              <li>20 users included</li>
              <li>10 GB of storage</li>
              <li>Priority email support</li>
              <li>Help center access</li>
            </ul>
            <button type="button" class="w-100 btn btn-lg btn-primary">Get started</button>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm border-primary">
          <div class="card-header py-3 text-bg-primary border-primary">
            <h4 class="my-0 fw-normal">Enterprise</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">$29<small class="text-body-secondary fw-light">/mo</small></h1>
            <ul class="list-unstyled mt-3 mb-4">
              <li>30 users included</li>
              <li>15 GB of storage</li>
              <li>Phone and email support</li>
              <li>Help center access</li>
            </ul>
            <button type="button" class="w-100 btn btn-lg btn-primary">Contact us</button>
          </div>
        </div>
      </div>
    </div>

    <h2 class="display-6 text-center mb-4">Compare plans</h2>

    <div class="table-responsive">
      <table class="table text-center">
        <thead>
          <tr>
            <th style="width: 34%;"></th>
            <th style="width: 22%;">Free</th>
            <th style="width: 22%;">Pro</th>
            <th style="width: 22%;">Enterprise</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row" class="text-start">Public</th>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
          </tr>
          <tr>
            <th scope="row" class="text-start">Private</th>
            <td></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
          </tr>
        </tbody>

        <tbody>
          <tr>
            <th scope="row" class="text-start">Permissions</th>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
          </tr>
          <tr>
            <th scope="row" class="text-start">Sharing</th>
            <td></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
          </tr>
          <tr>
            <th scope="row" class="text-start">Unlimited members</th>
            <td></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
          </tr>
          <tr>
            <th scope="row" class="text-start">Extra security</th>
            <td></td>
            <td></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
          </tr>
        </tbody>
      </table>
    </div>

</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" aria-label="Fifth navbar example">
    <div class="container-fluid">
       <%= link_to (image_tag('trees-icon.svg')), root_path, class: "navbar-brand", style: "width: 40px" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse " id="navbarsExample05">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0 justify-content-md-center">
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
             <%=  link_to "New Tree", new_tree_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
             <%=  link_to "Your Trees", trees_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
             <%=  link_to "Pricing", home_pricing_path, class: "nav-link" %>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Authentication</a>
            <ul class="dropdown-menu">
              <li><%= link_to "Log in", new_user_session_path, class: "dropdown-item" %></li>
              <li><%= link_to "Sign up", new_user_registration_path, class: "dropdown-item" %></li>
              <% if user_signed_in? %>
              <li><%= link_to "Log out", destroy_user_session_path , class: "dropdown-item"%></li>
              <% end %>
            </ul>
          </li>
        </ul>

      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%# javascript_importmap_tags %>
    <%= javascript_include_tag 'application', defer:true %>
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }

      .bd-mode-toggle {
        z-index: 1500;
      }

      .bd-mode-toggle .dropdown-menu .active .bi {
        display: block !important;
      }
    </style>

  </head>

  <body>


    <%= render 'layouts/header' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

<main class="container py-3">
  <%= yield %>
</main>


    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/trees/_form.html.erb
<%= form_with(model: tree) do |form| %>

<div class="ml-20 w-50 p-3">
  <% if tree.errors.any? %>
    <div  style="color: red">
      <h2><%= pluralize(tree.errors.count, "error") %> prohibited this tree from being saved:</h2>

      <ul>
        <% tree.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name , class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :x, style: "display: block" %>
    <%= form.url_field :x , class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :instagram, style: "display: block" %>
    <%= form.url_field :instagram , class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :youtube, style: "display: block" %>
    <%= form.url_field :youtube, class: "form-control" %>
  </div>

  <div class="form-group" style="display: none">
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id, value: current_user.id , class: "form-control"%>
  </div>

  <div class="form-group mb-10" style="margin-bottom: 10px">
    <%= form.label :style, style: "display: block" %>
    <%= form.select :style, [["Green", "green"], ["Pink", "pink"], ["Red", "red"]], class: "form-controll" %>
  </div>

  <div class="mt-10" >
    <%= form.submit :class, class: "btn btn-primary" %>
  </div>
</div>

<% end %>

app/views/trees/_tree.html.erb
<div style="background-color: <%= tree.style %>; width: 40%" id="<%= dom_id tree %>">
  <p>
    <strong>Name:</strong>
    <%= tree.name %>
  </p>

  <p>
    <strong>X:</strong>
    <%= tree.x %>
  </p>

  <p>
    <strong>Instagram:</strong>
    <%= tree.instagram %>
  </p>

  <p>
    <strong>Youtube:</strong>
    <%= tree.youtube %>
  </p>


</div>

app/views/trees/edit.html.erb
<h1>Editing tree</h1>

<%= render "form", tree: @tree %>

<br>

<div>
  <%= link_to "Show this tree", @tree %> |
  <%= link_to "Back to trees", trees_path %>
</div>

app/views/trees/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Trees</h1>

<div id="trees">
  <% @trees.each do |tree| %>
    <%= render tree %>
    <p>
      <%= link_to "Show this tree", tree %>
    </p>
  <% end %>
</div>

<%= link_to "New tree", new_tree_path %>

app/views/trees/new.html.erb
<h1>New tree</h1>

<%= render "form", tree: @tree %>

<br>

<div>
  <%= link_to "Back to trees", trees_path %>
</div>

app/views/trees/show.html.erb
<p style="color: green"><%= notice %></p>


<%= render @tree %>

<div>
  <% if user_signed_in? && current_user.id == @tree.user_id %>
  <%= link_to "Edit this tree", edit_tree_path(@tree) %>
  <%= link_to "Back to trees", trees_path %>
  <%= button_to "Destroy this tree", @tree, method: :delete %>
  <% end %>
  |


</div>